/**
 * RT — finishing a cut you already started.
 *
 * The gesture is unremarkable: cut halfway into something, lift, then go back in
 * and push through. It is also the ONLY way to sever anything at depth, where
 * the object is thousands of times the eraser and no single stroke reaches
 * across it — which is why Kobin met it constantly and why it looked like a bug
 * about zooming. It is not. It reproduces at level 0, at 1x, in two gestures.
 *
 * Why it failed: the second eraser's boundary is generated by the same pen
 * radius along the same path, so it COINCIDES with the boundary the first one
 * left. `circleCircle` divides by the distance between centres and `segSeg` by
 * the cross product of the directions, so coincident curves report no crossing
 * at all — and the fragments were then classified by a winding query taken at a
 * midpoint sitting exactly on the other shape's boundary, where there is no
 * answer to give. `pieceOverlap` plus the orientation rule in
 * `shapeBooleanOnce` are the fix.
 *
 * Measured before it: 13% of a stroke destroyed, a third piece invented, and a
 * chord drawn straight across the ink. The same cut with the pen ONE UNIT wider
 * was always clean, which is the control RT-1 and RT-2 are built on — a wider
 * eraser cannot possibly remove less ink than a narrower one over the same path.
 */
import fs from "fs";
import path from "path";
import { useEngines, mkEngine, drawStroke, erase } from "./__testkit__/harness";
import { loopsArea, pieceOverlap } from "./geometry/arcShape";
import { loadFixture } from "./__testkit__/legacyFixture";

jest.setTimeout(600000);
useEngines();

const ink = (E) => {
    const out = [];
    for (const L of E.doc.levels()) for (const o of E.doc.at(L)) if (!o.erase && o.loops) out.push(o);
    return out;
};
const area = (E) => ink(E).reduce((s, o) => s + Math.abs(loopsArea(o.loops)), 0);
// Areas measured IN ONE FRAME'S UNITS. A native three levels down measures the
// same ink 3000^3 times larger in its own frame, so a plain sum over levels is
// not a quantity at all — it changes when a cede moves ink from one level to
// the next without a pixel of it being erased.
const areaAt = (E, F) => {
    let t = 0;
    for (const L of E.doc.levels()) {
        const f = E.lm.frameFactor(L, F);
        if (f == null) continue;
        for (const o of E.doc.at(L)) if (!o.erase && o.loops) t += Math.abs(loopsArea(o.loops)) * f * f;
    }
    return t;
};

// One fat stroke, cut halfway, then finished. `size2` and `dx` are the two knobs
// that decide whether the second eraser's boundary lands on the first one's.
const cutTwice = (E, { size2 = 60, dx = 0, zoom = 1, y1 = 620 } = {}) => {
    drawStroke(E, [[200, 430], [750, 450], [1300, 430]], 220);
    if (zoom !== 1) {
        E.cam.set({ activeLevel: 0, frame: "0", inScale: zoom,
            inPanX: (1 - zoom) * 752, inPanY: (1 - zoom) * 434 });
    }
    const S = (x, y) => [752 + (x - 752) * zoom, 434 + (y - 434) * zoom];
    erase(E, [S(752, 300), S(752, 426)], 60);
    const mid = area(E);
    erase(E, [S(752 + dx, 380), S(752 + dx, y1)], size2);
    return { mid, after: area(E), pieces: ink(E).length, seals: E._boolFailures || 0 };
};

describe("RT-1 — a retraced cut keeps the ink the eraser never touched", () => {
    test("same pen, same path: severs, seals nothing, removes LESS than a wider pen", () => {
        const E = mkEngine(1504, 868);
        const same = cutTwice(E);
        const W = mkEngine(1504, 868);
        const wider = cutTwice(W, { size2: 61 });

        expect(same.seals).toBe(0);
        expect(wider.seals).toBe(0);
        expect(same.pieces).toBe(2);
        expect(wider.pieces).toBe(2);
        // The inequality that used to fail by 13% of the whole object: a 60-unit
        // eraser sweeps less ground than a 61-unit one over the same path, so it
        // must leave MORE ink behind.
        expect(same.after).toBeGreaterThan(wider.after);
        // ...and only a little more. A large gap means something other than the
        // extra unit of pen decided it.
        expect((same.after - wider.after) / wider.after).toBeLessThan(0.02);
    });

    test("a second cut INSIDE the first one's channel changes nothing at all", () => {
        const E = mkEngine(1504, 868);
        drawStroke(E, [[200, 430], [750, 450], [1300, 430]], 220);
        erase(E, [[752, 300], [752, 426]], 60);
        const before = area(E), n = ink(E).length;
        erase(E, [[752, 320], [752, 410]], 60);       // strictly inside, same pen
        expect(area(E) / before).toBeCloseTo(1, 6);
        expect(ink(E).length).toBe(n);
        expect(E._boolFailures || 0).toBe(0);
    });
});

describe("RT-2 — not about zoom, not about how much was left to cut", () => {
    // The original sweep: every RETRACE sealed, every far-side approach was
    // clean, and neither the in-level zoom nor the remaining gap made any
    // difference. Every cell has to come out clean now.
    for (const zoom of [1, 30, 130]) {
        for (const size2 of [60, 61]) {
            test(`zoom x${zoom}, second pen ${size2}`, () => {
                const E = mkEngine(1504, 868);
                const r = cutTwice(E, { zoom, size2 });
                expect(r.seals).toBe(0);
                expect(r.pieces).toBe(2);
            });
        }
    }
    for (const dx of [3, 20]) {
        test(`same pen, path offset ${dx} units (no coincidence)`, () => {
            const E = mkEngine(1504, 868);
            const r = cutTwice(E, { dx });
            expect(r.seals).toBe(0);
            expect(r.pieces).toBe(2);
        });
    }
});

describe("RT-3 — pieceOverlap sees what the intersectors cannot", () => {
    const L = (a, b) => ({ line: true, A: a, B: b });
    const arc = (C, r, a0, sweep) => ({
        line: false, C, r, a0, sweep,
        A: [C[0] + r * Math.cos(a0), C[1] + r * Math.sin(a0)],
        B: [C[0] + r * Math.cos(a0 + sweep), C[1] + r * Math.sin(a0 + sweep)],
    });
    test("collinear segments overlap; parallel-but-apart ones do not", () => {
        const p = L([0, 0], [10, 0]);
        expect(pieceOverlap(p, L([4, 0], [14, 0]), 1e-9)).toMatchObject({ same: true });
        expect(pieceOverlap(p, L([14, 0], [4, 0]), 1e-9)).toMatchObject({ same: false });
        expect(pieceOverlap(p, L([4, 0.5], [14, 0.5]), 1e-9)).toBeNull();
        expect(pieceOverlap(p, L([12, 0], [20, 0]), 1e-9)).toBeNull();   // beyond the end
        const ov = pieceOverlap(p, L([4, 0], [14, 0]), 1e-9);
        expect(ov.s[0]).toBeCloseTo(0.4, 12);
        expect(ov.s[1]).toBeCloseTo(1, 12);
    });
    test("co-circular arcs overlap; a different radius or centre does not", () => {
        const p = arc([0, 0], 5, 0, Math.PI);
        expect(pieceOverlap(p, arc([0, 0], 5, Math.PI / 2, Math.PI), 1e-9)).toMatchObject({ same: true });
        expect(pieceOverlap(p, arc([0, 0], 5, Math.PI * 1.5, -Math.PI), 1e-9)).toMatchObject({ same: false });
        expect(pieceOverlap(p, arc([0, 0], 5.5, 0, Math.PI), 1e-9)).toBeNull();
        expect(pieceOverlap(p, arc([1, 0], 5, 0, Math.PI), 1e-9)).toBeNull();
        const ov = pieceOverlap(p, arc([0, 0], 5, Math.PI / 2, Math.PI), 1e-9);
        expect(ov.s[0]).toBeCloseTo(0.5, 12);
        expect(ov.s[1]).toBeCloseTo(1, 12);
    });
    test("a line and an arc never coincide", () => {
        expect(pieceOverlap(L([0, 0], [10, 0]), arc([0, 0], 5, 0, Math.PI), 1e-9)).toBeNull();
    });
});

// ---------------------------------------------------------------------------
// RT-4 — Kobin's own session, replayed
// ---------------------------------------------------------------------------
//
// `20-54-08` and `20-55-00` are the same session 52 seconds apart: their
// journals share the prefix d1 e2 ... e32, and the later one adds e34 e38 e40
// e42. So the earlier snapshot is EXACTLY the state before the failure, and the
// later journal carries the gestures that produced it — pointer paths in frame
// coordinates, with the frame, the in-level zoom and the eraser size he used.
//
// e42 is the cut that severed the object at level 4, and the one that reported
// 58 open chains.
const DIR = path.join(process.cwd(), ".kobin-reports");
const report = (frag) => {
    if (!fs.existsSync(DIR)) return null;
    const f = fs.readdirSync(DIR).find((x) => x.includes(frag));
    return f ? JSON.parse(fs.readFileSync(path.join(DIR, f), "utf8")) : null;
};

describe("RT-4 — the reported failure, replayed from his own gestures", () => {
    test("e34, e38, e40, e42 all land, and none of them needs a chord", () => {
        const before = report("20-54-08"), after = report("20-55-00");
        if (!before || !after) return;                    // fixtures absent
        const E = mkEngine(before.screen.w, before.screen.h);
        loadFixture(E, before.snapshot);
        const seen = new Set(before.journal.map((j) => j.id));
        const rest = after.journal.filter((j) => j.kind === "erase" && !seen.has(j.id));
        expect(rest.map((g) => g.id)).toEqual([34, 38, 40, 42]);

        const results = [];
        for (const g of rest) {
            let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
            for (const [x, y] of g.pts) {
                x0 = Math.min(x0, x); x1 = Math.max(x1, x);
                y0 = Math.min(y0, y); y1 = Math.max(y1, y);
            }
            const s = g.inScale;
            const panX = before.screen.w / 2 - ((x0 + x1) / 2) * s;
            const panY = before.screen.h / 2 - ((y0 + y1) / 2) * s;
            E.cam.set({ activeLevel: g.level, frame: g.frame, inScale: s, inPanX: panX, inPanY: panY });
            E._render();
            const scr = g.pts.map(([x, y]) => [x * s + panX, y * s + panY]);
            const seals0 = E._boolFailures || 0;
            const area0 = areaAt(E, g.frame);
            erase(E, scr, g.px);
            // What the eraser actually swept: its width along its own path, plus
            // its round ends. Nothing it removes can exceed that.
            let len = 0;
            for (let i = 1; i < g.pts.length; i++) {
                len += Math.hypot(g.pts[i][0] - g.pts[i - 1][0], g.pts[i][1] - g.pts[i - 1][1]);
            }
            const swept = g.lwFrame * len + Math.PI * (g.lwFrame / 2) ** 2;
            results.push({ id: g.id, seals: (E._boolFailures || 0) - seals0, removed: area0 - areaAt(E, g.frame), swept });
        }
        for (const r of results) {
            expect(r.seals).toBe(0);
            // THE INVARIANT, and the one the failure broke by four orders of
            // magnitude: e42's eraser swept 0.83 square units and took 22,722
            // with it, which is what "the piece changes shape dramatically"
            // looks like in a number. The slack is for the ends, which are round
            // rather than square.
            expect(r.removed).toBeLessThan(r.swept * 1.6);
            expect(r.removed).toBeGreaterThanOrEqual(0);
        }
        // ...and the object does NOT come apart. His last gesture removed 1 unit
        // of a 631-million-unit object: it never reached through the bridge. The
        // severance he saw was the chords tearing it in half, which is why he
        // reported the pieces as split but "not split correctly".
        const keys = new Set(ink(E).map((o) => E.doc.editKey(o)));
        expect(keys.size).toBe(1);
    });
});
